# Site settings
title: Lolli.Cloud
email: posta@danielelolli.it
description: Diario personale di un webmaster a tempo perso.
baseurl: # the subpath of your site, e.g. /blog
url: https://lolli.cloud # the base hostname & protocol for your site
domain: https://lolli.cloud

# Identity
your-name: Daniele Lolli (UncleDan)
your-title: Esperto Software Paghe e Webmaster a tempo perso

# Social settings
500px_url: https://500px.com/uncledan
facebook_url: https://facebook.com/uncledan
github_url: https://github.com/Lolli-Cloud/Lolli-Cloud.github.io
googleplus_url: https://plus.google.com/+DanieleLolli74
instagram_url: https://www.instagram.com/uncledan74
linkedin_url: http://www.linkedin.com/in/danielelolli
pinterest_url: https://www.pinterest.it/uncledan74
slack_url: http://www.twitter.com/uncledan74
twitter_url: http://www.twitter.com/uncledan74

# Build settings
markdown: kramdown
